services:
  - type: web
    name: taskflow-pro-api
    env: docker
    plan: free

    # Root directory where Dockerfile is located
    rootDir: backend

    # Auto deploy on git push
    autoDeploy: true

    envVars:

      # --- Database config ---
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

      # --- JWT ---
      - key: JWT_SECRET
        sync: false

      # --- CORS ---
      - key: CORS_ORIGINS
        value: https://taskflowprowebapp.netlify.app